services:
  postgres-news:
    image: postgres:18.1-alpine3.23
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}" ]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - news-volume:/var/lib/postgresql

  # redis:
  #   image: redis:7-alpine
  # api:
  #   build: .
  #   ports:
  #     - "8080:8080"
  #     - "9090:9090"
  #   depends_on:
  #     postgres:
  #       condition: service_healthy
  #       restart: true
  #     redis:
  #       condition: service_started
  #   entrypoint: [ "/app/wait-for.sh", "postgres:5432", "--", "/app/start.sh" ]
  #   command: [ "/app/main" ]

volumes:
  news-volume:
  news-backup:
