services:
  minio:
    env_file: ".env"
    image: minio/minio:RELEASE.2025-09-07T16-13-09Z-cpuv1
    ports:
      - "${MINIO_SERVER_PORT}:9000"
      - "${MINIO_BROWSER_PORT}:9001"
    volumes:
      - /tmp/minio/data:/data
    command: ["server", "/data", "--console-address", ":9001"]
