services:
  postgres-auth:
    image: postgres:17.7-alpine3.22
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}" ]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - auth-volume:/var/lib/postgresql/data

volumes:
  auth-volume:
